---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: dealc
  namespace: newsletter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dealc
  template:
    metadata:
      labels:
        app: dealc
    spec:
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        beta.kubernetes.io/arch: amd64
        # We need newer CPU instruction set
        # https://stackoverflow.com/a/49169125/5093093
        kubernetes.io/hostname: panda
      containers:
        - name: dealc
          image: 'porkbrain/newsletter:dealc-0.1.0'
          imagePullPolicy: IfNotPresent # it's too big
          resources:
            requests: # min
              memory: 128Mi
              cpu: 200m
            limits: # max
              memory: 512Mi
              cpu: 600m
          env:
            - name: HTTP_PORT
              value: '80'

---
kind: Service
apiVersion: v1
metadata:
  name: dealc
  namespace: newsletter
spec:
  selector:
    app: dealc
  ports:
    - name: http
      protocol: TCP
      port: 8081 # used by predictor.yml
      targetPort: 80

