---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ocr
  namespace: newsletter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocr
  template:
    metadata:
      labels:
        app: ocr
    spec:
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      containers:
        - name: ocr
          image: 'porkbrain/newsletter:ocr-0.2.0'
          imagePullPolicy: Always
          resources:
            requests: # min
              memory: 64Mi
              cpu: 100m
            limits: # max
              memory: 128Mi
              cpu: 300m
          env:
            - name: RUST_LOG
              value: 'error,ocr=info'
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws
                  key: key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws
                  key: secret
            - name: AWS_DEFAULT_REGION
              valueFrom:
                secretKeyRef:
                  name: aws
                  key: region
            - name: GCP_SECRET
              valueFrom:
                secretKeyRef:
                  name: gcp-ocr
                  key: json
            - name: OCR_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: ocr
                  key: ocr_bucket_name
            - name: INPUT_QUEUE_URL
              valueFrom:
                secretKeyRef:
                  name: ocr
                  key: input_queue_url

