---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: newsletter-pv
  namespace: newsletter
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /var/local/newsletter
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - gloss

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: newsletter-pvc
  namespace: newsletter
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi


